DELETE http://localhost:3001/api/blogs/66437af5a4e2ca8f52b76cc1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2UiLCJpZCI6IjY2NDM3YThiYTRlMmNhOGY1MmI3NmM5NyIsImlhdCI6MTcxNTY5ODMyNX0.hQFH1qb3dbSFhH5MtCwuze0CV-Kqb2yAuYsfegYKzvA